name: deploy get list of words by word lambda

on:
  push:
    paths:
      - 'getListOfWordsByWord_Lambda/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: cd getListOfWordsByWord_Lambda && yarn
      - name: Run tests
        run: cd getListOfWordsByWord_Lambda && yarn test
      - name: Install zip tools
        uses: montudor/action-zip@v0.1.0
      - name: Zip the lambda
        run:  cd getListOfWordsByWord_Lambda && zip -r getListOfWordsByWord.zip .
      - name: AWS CLI V2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:590184059304:function:getListOfWordsByWord \
            --zip-file fileb://getListOfWordsByWord_Lambda/getListOfWordsByWord.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
